#!/usr/bin/env bash -l
# ------------------------------------------------------------------------------
#  ~/script/build
#  J1 Docker - Helper script for the (image) built process
#
#  Product/Info:
#  https://jekyll-one.com
#
#  Copyright (C) 2018 Juergen Adams
#
#  J1 Template is licensed under the MIT License.
#  See: https://github.com/jekyll-one/j1_template_mde/blob/master/LICENSE
# ------------------------------------------------------------------------------
# NOTE:
#
# ------------------------------------------------------------------------------
set -e

bundle exec docker-template build $DOCKER_REPO \
  --no-push --force --squash || \
      exit $?
